### ISSUE TITLE
공휴일을 어떻게 아는가?

### ISSUE THREAD

**Issue by Raon1123** [Raon1123/bus-hexa#1]
토요일 일요일 및 공휴일 시간표가 다른데, 공휴일을 임시로 하드코딩 해서 넣음,

[Link](https://www.data.go.kr/iim/api/selectAPIAcountView.do)

**Comment by jaehwan1912** [comment]
현재 특일정보 api를 사용해 공휴일인지 확인중이므로  이슈 닫습니다!
