### ISSUE TITLE
도착정보 crawling

### ISSUE THREAD

**Issue by Raon1123** [Raon1123/bus-hexa#3]
도착정보의 경우 현재 요청이 들어오면 울산 API로 부터 가져오는 방식입니다.
이를 백엔드에서 주기적(30초 이내)로 크롤링을 시도하여, DB에 저장하고 DB에서 꺼내오는 방식으로 바꾸는 작업이 요구됩니다.

**Comment by jaehwan1912** [comment]
적용된 사항입니다.
이슈 닫겠습니다.
